### ISSUE TITLE
Not turning on after shutting off

### ISSUE THREAD

**Issue by lop3r87** [WolfRevo/climate.spzb0001_thermostat#4]
Hi! Im using this with a eurotronic connected via zha. It works until the temp is reached then it shuts off and wont turn back on again even if temperature goes low. 
Only way to get it going again is to turn it back on in the original entity or on the physical thermostat then it does the same thing again

**Comment by WolfRevo** [comment]
Hi. The version for HACS (in this repo) is built to work with deCONZ. ZHA uses a different way of handling the HVAC modes (On, Off, Auto etc.). I will have a look tomorrow into my local repo. There should be a unofficial version I used internally with ZHA. I can provide this one for you if you like to use it as a custom integration (without the possibility of using HACS in this case).

**Comment by lop3r87** [comment]
That would be awesome thanx! 👍😊

**Comment by WolfRevo** [comment]
You know how to use a custom integration without HACS?
Then feel free to use the [zha dev version](https://github.com/WolfRevo/climate.spzb0001_thermostat/blob/9eb0b6f938ee71cce7bedd56c60e315b5696f206/custom_components/spzb0001_thermostat/climate.py) 😉 hopefully there weren't any breaking changes in zha since I changed my thermostats.

**Comment by lop3r87** [comment]
Yes i do, i dont use hacs at all. Thank you very much! :100: :1st_place_medal:

**Comment by WolfRevo** [comment]
You are welcome. If you have any issues send me some debug output so I may be able to help. Also please let me know if it works for you.

**Comment by lop3r87** [comment]
It has been working great now since yesterday. Stable temperature! Thank you very much!! 💥💯💪

**Comment by WolfRevo** [comment]
I'm glad that I could help!

**Comment by brainpaincgn** [comment]
Hello!
I played around with the HACS integration yesterday and had similar problem. As I am new to HASS I don't know how to use custom intergrations without HACS. I am using the SONOFF ZigBee USB device. I removed the integration, removed everything from configuration.yaml, but the entity I created is still shown and is marked as write protected.
Could please point me in the right direction? 

Thanks in advance
<img width="1362" alt="Bildschirmfoto 2022-12-11 um 12 44 49" src="https://user-images.githubusercontent.com/6752108/206901668-4215f6a3-ff93-4884-ab56-5887822636a6.png">

**Comment by WolfRevo** [comment]
Hey @brainpaincgn,

first please take a look here: https://smartme.pl/en/adding-custom-component-to-home-assistant/
Second: honestly I don't really maintain this component any more as I don't use DeCONz but ZHA now and I use different thermostats as well. I will let the code avaible through github but I will brand the component as deprecated otherwise people run into problems which I can't help with anymore. Sorry for that.
Nevertheless you can use it as a custom component on your own using the provided description above and the link I gave to lop3r87 but you kneed to understand what the component is doing, how it works, etc.

Honestly I don't know how you can get rid of the phantom entity. You might get better help with this in the official HA forums as this is more related to database topics I guess.
